services:
  very-simple-notes:
    image: jpyles0524/very_simple_notes:latest
    build:
      context: ./
    container_name: very-simple-notes
    ports:
      - "8000:8000"
    networks:
      - vsn
  mongo:
    container_name: vsn-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - vsn
networks:
  vsn:
    external: true
    name: vsn
