version: "3"
services:
  frontend:
    build:
      context: ./
    container_name: frontend
    ports:
      - "8000:8000"
  mongo:
    container_name: vsn-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
