name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.update_version.outputs.VERSION }}

    steps:
      - uses: actions/checkout@v4

      - name: Update version
        id: update_version
        run: |
          new_version=$(./versioning.sh patch)
          echo "VERSION=$new_version" >> $GITHUB_OUTPUT

      - name: Display version
        run: echo "The new version is ${{ steps.update_version.outputs.VERSION }}"

  build:
    runs-on: ubuntu-latest
    needs: update-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/very_simple_notes:${{ needs.update-version.outputs.VERSION }}

  helm-deploy:
    runs-on: ubuntu-latest
    needs: update-version
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Display version
        run: echo "Updating Helm Chart to version ${{ needs.update-version.outputs.VERSION }}"

      - name: Publish Helm Chart
        uses: jaypyles/helm-chart-publisher@main
        with:
          chart_path: "./charts/very-simple-notes"
          chart_name: "very-simple-notes"
          gpat_token: "${{ secrets.GPAT_TOKEN }}"
          helm_repo_url: "${{ secrets.HELM_URL }}"
          target_repo: "jaypyles/helm-charts"
          branch: "master"
          new_version: "${{ needs.update-version.outputs.VERSION }}"
