name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/very_simple_notes:latest

  helm-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Helm Chart
        uses: jaypyles/helm-chart-publisher@main
        with:
          chart_path: './charts/very-simple-notes'
          chart_name: 'very-simple-notes'
          github_token: ${{ secrets.GPAT_TOKEN }}
          helm_repo_url: '${{ secrets.HELM_URL }}'
          target_repo: 'jaypyles/helm-charts'
          branch: 'main'
          new_version: '1.0.1'
